export const connections = [
    {
        id: 1,
        content: '#1',
        group: 1,
        groupTitle: 'Group 1',
    },
    {
        id: 2,
        content: '#2',
        group: 1,
        groupTitle: 'Group 1',
    },
    {
        id: 3,
        content: '#3',
        group: 1,
        groupTitle: 'Group 1',
    },
    {
        id: 4,
        content: '#4',
        group: 1,
        groupTitle: 'Group 1',
    },
    {
        id: 5,
        content: '#5',
        group: 2,
        groupTitle: 'Group 2',
    },
    {
        id: 6,
        content: '#6',
        group: 2,
        groupTitle: 'Group 2',
    },
    {
        id: 7,
        content: '#7',
        group: 2,
        groupTitle: 'Group 2',
    },
    {
        id: 8,
        content: '#8',
        group: 2,
        groupTitle: 'Group 2',
    },
    {
        id: 9,
        content: '#9',
        group: 3,
        groupTitle: 'Group 3',
    },
    {
        id: 10,
        content: '#10',
        group: 3,
        groupTitle: 'Group 3',
    },
    {
        id: 11,
        content: '#11',
        group: 3,
        groupTitle: 'Group 3',
    },
    {
        id: 12,
        content: '#12',
        group: 3,
        groupTitle: 'Group 3',
    },
    {
        id: 13,
        content: '#13',
        group: 4,
        groupTitle: 'Group 4',
    },
    {
        id: 14,
        content: '#14',
        group: 4,
        groupTitle: 'Group 4',
    },
    {
        id: 15,
        content: '#15',
        group: 4,
        groupTitle: 'Group 4',
    },
    {
        id: 16,
        content: '#16',
        group: 4,
        groupTitle: 'Group 4',
    },
]